Feature/407342 fowler welch
DEFRA/trade-exportscore-plp pull request #17
Opened 2024-07-16 09:51 UTC by mehnpat1199

# Pull Request Details

## What this PR does / why we need it:
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item AB#213700 and builds on #3376 (link to ADO Build ID URL)*

## Special notes for your reviewer
*Any specific actions or notes on review?*

## Testing
*Any relevant testing information and pipeline runs.*

## Checklist (please delete before completing or setting auto-complete)
- [ ] Story Work items associated (not Tasks)
- [ ] Successful testing run(s) link provided
- [ ] Title pattern should be `{work item number}: {title}`
- [ ] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests

## How does this PR make you feel:
![gif]([https://giphy.com/)

2024-07-17 14:51 UTC, padget11 approved these changes

2024-07-17 19:21 UTC, jaybarden commented on test/unit/services/parser-service.test.js
> +          M: 'NIIRMS Dispatch number',
Is this version of NIRMS supposed to have 2 "I"s? If so, please ignore me

2024-07-17 19:22 UTC, jaybarden reviewed
I added a comment in the test file but will add here to - there are a couple of places where NIRMS is NIIRMS - is that correct? Apologies if it is, it just looks wrong to me.

2024-07-18 08:42 UTC, jaybarden submitted a review, later dismissed
All looks good to me and apologies again for the "NIRMS/NIIRMS" question

2024-07-18 08:46 UTC, padget11 approved these changes

2024-07-18 08:49 UTC, dynamicmonkeys requested changes

2024-07-18 08:49 UTC, dynamicmonkeys commented on app/services/parser-service.js
> +      M: 'NIIRMS Dispatch number',
Please change to NIRMS

2024-07-18 08:49 UTC, dynamicmonkeys commented on test/unit/services/parser-service.test.js
> +          M: 'NIIRMS Dispatch number',
Please change to NIRMS

2024-07-18 08:49 UTC, dynamicmonkeys commented on test/unit/services/parser-service.test.js
> +          M: 'NIIRMS Dispatch number',
Please change to NIRMS

2024-07-18 08:49 UTC, dynamicmonkeys commented on test/unit/services/parser-service.test.js
> +        M: 'NIIRMS Dispatch number',
Please change to NIRMS

2024-07-18 08:49 UTC, dynamicmonkeys commented on package.json
> +  "version": "0.1.26",
Please merge in main and bump this

2024-07-18 08:59 UTC, dynamicmonkeys commented on app/services/parser-service.js
> +      M: 'NIIRMS Dispatch number',
Ignore me, thanks @padget11 for info :)

2024-07-18 08:59 UTC, dynamicmonkeys commented on test/unit/services/parser-service.test.js
> +          M: 'NIIRMS Dispatch number',
Ignore me, thanks @padget11 for info :)

2024-07-18 08:59 UTC, dynamicmonkeys commented on test/unit/services/parser-service.test.js
> +          M: 'NIIRMS Dispatch number',
Ignore me, thanks @padget11 for info :)

2024-07-18 08:59 UTC, dynamicmonkeys commented on test/unit/services/parser-service.test.js
> +        M: 'NIIRMS Dispatch number',
Ignore me, thanks @padget11 for info :)

2024-07-18 09:35 UTC, dynamicmonkeys approved these changes

2024-07-18 09:36 UTC, merged